"""empty message

Revision ID: 7a8f0b2d4ff7
Revises: 
Create Date: 2025-04-24 11:28:31.675048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a8f0b2d4ff7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messageHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(length=50), nullable=False),
    sa.Column('recipient_id', sa.String(length=50), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('message_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('titulo_id', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('cartorio_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_accounts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('wb_accounts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('business_account_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('verified_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'phone_id', 'business_account_id', name='wb_accounts_pkey'),
    sa.UniqueConstraint('business_account_id', name='wb_accounts_business_account_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('zapenviados',
    sa.Column('messageid', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('titulo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('whatsapp', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('wa_id', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    sa.Column('message_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('accepted', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rejected', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('datainsert', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('mesano_insert', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['titulo_id'], ['titulos.id'], name='zapenviados_titulo_id_fkey'),
    sa.PrimaryKeyConstraint('titulo_id', 'whatsapp', 'mesano_insert', name='zapenviados_pkey')
    )
    op.create_table('cartorios',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cartorios_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cartorios_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('devedores',
    sa.Column('titulo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('documento', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['titulo_id'], ['titulos.id'], name='devedores_titulo_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('titulo_id', 'documento', name='devedores_pkey')
    )
    op.create_table('message_history',
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('titulo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('error_code', sa.VARCHAR(length=7), autoincrement=False, nullable=True)
    )
    op.create_table('verifica_whatsapp',
    sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('validado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('message_content', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('templates',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wbaccount_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['wbaccount_id'], ['wb_accounts.business_account_id'], name='templates_wbaccount_id_fkey'),
    sa.PrimaryKeyConstraint('name', 'wbaccount_id', name='templates_pkey')
    )
    op.create_table('contatos',
    sa.Column('documento', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('validado', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('detalhes', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('documento', 'telefone', name='contatos_pkey')
    )
    op.create_table('agendamentos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_disparo', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='agendamentos_pkey')
    )
    op.create_table('titulos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cartorio_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('protocolo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('credor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('valorprotestado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('numerotitulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dataprotesto', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mesano', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valorboleto', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('datainsert', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('mesano_insert', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cartorio_id'], ['cartorios.id'], name='titulos_cartorio_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='titulos_pkey'),
    sa.UniqueConstraint('protocolo', 'mesano_insert', name='titulos_protocolo_mesano_key')
    )
    op.drop_table('usuario')
    op.drop_table('messageHistory')
    # ### end Alembic commands ###
