"""empty message

Revision ID: 963dd517c2e8
Revises: 
Create Date: 2025-02-24 22:31:14.679928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963dd517c2e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('cartorio_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
